name: Move Tasks to In Progress

on:
  pull_request:
    types: [opened]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find project card ID
        id: find-card
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the issue or pull request number
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Get the project card ID for the linked issue or pull request
          CARD_ID=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/projects" | jq -r '.[0].id')

          # Save the card ID as an output for the next step
          echo "card_id=${CARD_ID}" >> $GITHUB_ENV

      - name: Move task to In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the ID of the "In Progress" column
          IN_PROGRESS_COLUMN_ID=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/projects/columns" | jq -r '.[] | select(.name=="In Progress").id')

          # Move the card to the "In Progress" column
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/projects/columns/cards/${CARD_ID}/moves" \
            -d '{
              "position": "top",
              "column_id": '"$IN_PROGRESS_COLUMN_ID"'
            }'
